"""add school houses

Revision ID: 1ba058ddcd7b
Revises: a1b2c3d4e5f6
Create Date: 2026-05-10 10:12:02.680549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba058ddcd7b'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_houses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_attendance_records_session', table_name='attendance_records')
    op.drop_index('ix_attendance_records_student_school', table_name='attendance_records')
    op.drop_index('ix_attendance_sessions_class_date_status', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_flagged', table_name='attendance_sessions')
    op.drop_index('ix_attendance_sessions_school_date', table_name='attendance_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_attendance_sessions_school_date', 'attendance_sessions', ['school_id', 'date'], unique=False)
    op.create_index('ix_attendance_sessions_flagged', 'attendance_sessions', ['school_id', 'is_flagged', 'review_outcome'], unique=False)
    op.create_index('ix_attendance_sessions_class_date_status', 'attendance_sessions', ['class_id', 'date', 'status'], unique=False)
    op.create_index('ix_attendance_records_student_school', 'attendance_records', ['student_id', 'school_id'], unique=False)
    op.create_index('ix_attendance_records_session', 'attendance_records', ['session_id'], unique=False)
    op.drop_table('school_houses')
    # ### end Alembic commands ###
