"""score audit trail

Revision ID: 2ad145424983
Revises: 1ba058ddcd7b
Create Date: 2026-05-10 10:54:13.617032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad145424983'
down_revision: Union[str, None] = '1ba058ddcd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_edit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('assessment_score_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('old_is_absent', sa.Boolean(), nullable=True),
    sa.Column('new_is_absent', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_after_submission', sa.Boolean(), nullable=True),
    sa.Column('is_after_lock', sa.Boolean(), nullable=True),
    sa.Column('changed_at_hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_score_id'], ['assessment_scores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_edit_logs')
    # ### end Alembic commands ###
