"""simplify subjects

Revision ID: 670d981cd433
Revises: 739ea410dac3
Create Date: 2026-05-14 20:07:53.850108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670d981cd433'
down_revision: Union[str, None] = '739ea410dac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the seeded "system" subjects (school_id NULL) — they're no
    # longer used; subjects are copied to school_subjects on creation.
    op.execute("DELETE FROM subjects WHERE school_id IS NULL")
    op.alter_column('subjects', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('subjects', 'level_group')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('level_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('subjects', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
