"""staff_qualifications_promotions_ges_ranks

Revision ID: 6aae545caf6d
Revises: e0d1f2eb6116
Create Date: 2026-05-12 17:04:11.566251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aae545caf6d'
down_revision: Union[str, None] = 'e0d1f2eb6116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ges_ranks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('staff_promotions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('from_rank', sa.String(length=150), nullable=True),
    sa.Column('to_rank', sa.String(length=150), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('promotion_type', sa.String(length=30), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_qualifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('year_obtained', sa.Integer(), nullable=True),
    sa.Column('cert_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('staff', sa.Column('license_number', sa.String(length=50), nullable=True))
    op.drop_column('staff', 'qualification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('qualification', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('staff', 'license_number')
    op.drop_table('staff_qualifications')
    op.drop_table('staff_promotions')
    op.drop_table('ges_ranks')
    # ### end Alembic commands ###
