"""add_missing_student_columns

Revision ID: e0d1f2eb6116
Revises: 3f8830433aca
Create Date: 2026-05-12 15:17:16.625998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d1f2eb6116'
down_revision: Union[str, None] = '3f8830433aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'notes')
    # ### end Alembic commands ###
